### ISSUE TITLE
App not working in android Lollipop 5.1

### ISSUE THREAD

**Issue by naman653** [fossasia/badge-magic-android#126]
**Describe the bug**
App crashes as soon as it starts.

**To Reproduce**
Try to launch the app in Android 5.1.

**Expected behavior**
App should run without crash.

**Logs**
```
java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
        at android.graphics.drawable.VectorDrawable$VectorDrawableState.createCachedBitmapIfNeeded(VectorDrawable.java:713)
        at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:280)
        at com.nilhcem.blenamebadge.ui.badge_preview.PreviewBadge.onDraw(PreviewBadge.kt:225)
        at android.view.View.draw(View.java:15495)
        at android.view.View.updateDisplayListIfDirty(View.java:14384)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:295)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:335)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2940)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2754)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2368)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1293)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6599)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
        at android.view.Choreographer.doCallbacks(Choreographer.java:603)
        at android.view.Choreographer.doFrame(Choreographer.java:572)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

**Smartphone Info:**

|                  | |
|---------------|-|
|Device              | Intex Cloud Flash|
|Android Version| Lollipop 5.1    |

**Would you like to work on the issue?**

No.

**Comment by adityastic** [comment]
I would like to work on this issue. Downloading the platform in Android Studio, Thanks for the information
