### ISSUE TITLE
IllegalArgumentException when SEND button click 3 times

### ISSUE THREAD

**Issue by itskshitizsh** [fossasia/badge-magic-android#32]
**Describe the bug**

App Stopped working due to FATAL EXCEPTION: main.

**To Reproduce**

Install App and allow Bluetooth, with no device connected. With empty field, click on SEND more than 3 times.

**Expected behavior**

If no device is connected, the device should give a message, may be in the form of Toast that device not connected or Scan could not find any device.

**Logs**

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nilhcem.blenamebadge, PID: 10565
    java.lang.IllegalArgumentException: scanner already started with given callback
        at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerImplLollipop.startScanInternal(BluetoothLeScannerImplLollipop.java:61)
        at no.nordicsemi.android.support.v18.scanner.BluetoothLeScannerCompat.startScan(BluetoothLeScannerCompat.java:112)
        at com.nilhcem.blenamebadge.device.bluetooth.ScanHelper.startLeScan(ScanHelper.kt:57)
        at com.nilhcem.blenamebadge.ui.message.MessagePresenter.sendBytes(MessagePresenter.kt:36)
        at com.nilhcem.blenamebadge.ui.message.MessagePresenter.sendBitmap(MessagePresenter.kt:25)
        at com.nilhcem.blenamebadge.ui.message.MessageActivity$onCreate$3.onClick(MessageActivity.kt:58)
        at android.view.View.performClick(View.java:6614)
        at android.view.View.performClickInternal(View.java:6587)
        at android.view.View.access$3100(View.java:784)
        at android.view.View$PerformClick.run(View.java:26125)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6715)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
I/Process: Sending signal. PID: 10565 SIG: 9
Application terminated.

**Screenshots**

![image](https://user-images.githubusercontent.com/24621468/51737911-d5d12880-20b3-11e9-901c-ee3226b2330e.png)

**Smartphone Info:**
|                            |                       |
|-------------------|----------------|
|Device                 |Nokia 5.1 Plus |
|Android Version  |Android Pie     |

**Would you like to work on the issue?**

Yes

**Comment by kshitij-99** [comment]
Can I work on this issue ?
