### ISSUE TITLE
App crashes when you try to delete an intermediate bitmap

### ISSUE THREAD

**Issue by harshshinde07** [fossasia/badge-magic-android#527]
**Describe the bug**

When you insert 2 or more bitmaps in the input field and try to delete any intermediate bitmap (i.e. any, except the last) the app crashes.

**To Reproduce**

1. Insert more than one bitmaps into the input field.
2. Try deleting any bitmap except the last.

**Expected behavior**

The bitmap before the cursor should get removed without causing the application to crash.

**Logs**
```
java.lang.NumberFormatException: For input string: "1«1"
        at java.lang.Integer.parseInt(Integer.java:608)
        at java.lang.Integer.parseInt(Integer.java:643)
        at org.fossasia.badgemagic.util.Converters.convertEditableToLEDHex(Converters.kt:188)
        at org.fossasia.badgemagic.ui.fragments.TextArtFragment.setPreview(TextArtFragment.kt:437)
        at org.fossasia.badgemagic.ui.fragments.TextArtFragment.access$setPreview(TextArtFragment.kt:64)
        at org.fossasia.badgemagic.ui.fragments.TextArtFragment$textChangedListener$1.onTextChanged(TextArtFragment.kt:206)
        at android.widget.TextView.sendOnTextChanged(TextView.java:9658)
        at android.widget.TextView.handleTextChanged(TextView.java:9752)
        at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12247)
        at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1275)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:583)
        at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:232)
        at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:227)
        at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:250)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:455)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6784)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
```

**Screenshots**

<img src="https://user-images.githubusercontent.com/25999879/68045131-d1026a80-fcfe-11e9-83d1-914575094d33.png" height=512>

As shown above, if you use backspace key now, the app will crash.

**Comment by tronku** [comment]
I want to work on this.

**Comment by adityastic** [comment]
@tronku sure
