### ISSUE TITLE
App Crashes While Deleting ClipArts In SavedClipArt 

### ISSUE THREAD

**Issue by refactor-droidyy** [fossasia/badge-magic-android#528]
**Describe the bug**

When you try to delete any saved clipart the app crashes.

**To Reproduce**

1. Draw one or more clipart.
2. Now Navigate to Saved Clipart section in Navigation drawer and try to delete any clipart.

**Expected behavior**

The selected clipart should be deleted and the app doesn't crash

**Logs**

 java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 1.
        at kotlin.collections.EmptyList.get(Collections.kt:34)
        at kotlin.collections.EmptyList.get(Collections.kt:22)
        at org.fossasia.badgemagic.viewmodels.SavedClipartViewModel.deleteClipart(SavedClipartViewModel.kt:18)
        at org.fossasia.badgemagic.adapter.SavedClipartsAdapter$onBindViewHolder$1.onClick(SavedClipartsAdapter.kt:29)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22465)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Screenshots**

![Screenshot_2019-11-02-12-22-46-093_org fossasia badgemagic](https://user-images.githubusercontent.com/44283521/68067373-f5e0f700-fd6b-11e9-878e-134c72d08de0.png)

Performing deletion on clicking (X)  the app crash

**Smartphone Info:**

Device - Xiomi Redmi 4A
Android Version -  Nought 7.1.2

**Comment by refactor-droidyy** [comment]
@mariobehling I want to work on this issue

**Comment by adityastic** [comment]
@refactor-droidyy go ahead

**Comment by tronku** [comment]
Can I work on this issue? It has been quite long I guess. I have resolved this issue.

**Comment by adityastic** [comment]
@tronku sure, go ahead
