### ISSUE TITLE
Cliparts size is 40x11 even though badge size is 44x11

### ISSUE THREAD

**Issue by johannesschweig** [fossasia/badge-magic-android#586]
First up, thanks for your amazing work on this app. Really love the easy way to change badges!
**Describe the bug**
I noticed that cliparts can only be created in a 40x11 px format (stored png also has this format). But the badge has a 44x11 px width. Any reason for that?

**To Reproduce**
Create a new clipart and fill it with pixels. Now go to "create badge" and insert it. There will be an area of 2px left and right of the clipart which will not have any red pixels.

**Expected behavior**
I would expect the canvas for new cliparts to be 44px wide.

**Screenshots**
Photo of the clipart:
![photo5208504173140749201](https://user-images.githubusercontent.com/10641030/71558410-4e263380-2a53-11ea-8d82-135c6a153d5e.jpg)
Photo of the badge with padding.
![photo5208648853409082519](https://user-images.githubusercontent.com/10641030/71558414-52525100-2a53-11ea-98d8-0ebcde0162dd.jpg)

**Smartphone Info:**
|Device         | Samsung Galaxy S5 (klte) |
|Android Version| 9 (Lineageos)    |
App version: 1.5.0

**Would you like to work on the issue?**
My android skills are low, so rather not.

**Comment by adityastic** [comment]
@johannesschweig glad you're liking our application. I'll take up this issue and get it fixed in the upcoming version asap. Feel free to track the progress of this issue here :). Regards

**Comment by Kamal-Sonani** [comment]
as labeled bug for width(40 to 44) , i'm trying for height 16px (led) instead of default 11px(led) to generate binary matrix data.

i simply tried with variable
badgeHeiight = 11 
to 
badgeHeiight = 16 
i got perfect view in app but when i fill any single char in text box , app just crashed & closed
**LOG CAT**
`08-01 12:42:57.192 32128-32128/org.fossasia.badgemagic E/DrawerActivity: OnCreate, false
08-01 12:43:00.642 32128-32128/org.fossasia.badgemagic E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.fossasia.badgemagic, PID: 32128
    java.lang.StringIndexOutOfBoundsException: length=22; regionStart=22; regionLength=2
        at java.lang.String.startEndAndLength(String.java:298)
        at java.lang.String.substring(String.java:1087)
        at org.fossasia.badgemagic.ui.custom.PreviewBadge.setValue(PreviewBadge.kt:499)
        at org.fossasia.badgemagic.ui.fragments.TextArtFragment.setPreview(TextArtFragment.kt:429)
        at org.fossasia.badgemagic.ui.fragments.TextArtFragment.access$setPreview(TextArtFragment.kt:63)
        at org.fossasia.badgemagic.ui.fragments.TextArtFragment$textChangedListener$1.afterTextChanged(TextArtFragment.kt:176)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:8041)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10354)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1043)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:560)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:34)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:704)
        at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:207)
        at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:188)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:286)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5628)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)`

Errors
       
        **at org.fossasia.badgemagic.ui.custom.PreviewBadge.setValue(PreviewBadge.kt:499)
        at org.fossasia.badgemagic.ui.fragments.TextArtFragment.setPreview(TextArtFragment.kt:429)
        at org.fossasia.badgemagic.ui.fragments.TextArtFragment.access$setPreview(TextArtFragment.kt:63)
        at org.fossasia.badgemagic.ui.fragments.TextArtFragment$textChangedListener$1.afterTextChanged(TextArtFragment.kt:176)**

**Any suggestions ?**

**Comment by adityastic** [comment]
@Kamal-Sonani We might have to do a lot of changes to the PreviewBadge, I wish I could help out but I have to spend time working rn. I could help but someone has to understand the math and the algorithms used to make that work.

**Comment by Kamal-Sonani** [comment]
Last hour i debug and finally i got succes.

In bitmap creation their is fixed value 11 ,
I changed it to badge.height & it works 👍

Thanks for sharing .

**Comment by adityastic** [comment]
> Last hour i debug and finally i got succes.
> 
> In bitmap creation their is fixed value 11 ,
> I changed it to badge.height & it works 👍
> 
> Thanks for sharing .

Good stuff mate ☺️

**Comment by akri16** [comment]
Is this still up?

**Comment by adityastic** [comment]
Yep, it is. Feel free to take it
